name: Feature Request
description: >
  Have a new feature you would like to see implemented?
  Use this template to request a new feature!

title: "[FEATURE] - "
labels: ["type: feature", "status: needs triage"]
assignees:
  - sh0ckR6

body:
  # Ensure the user is not requesting a duplicate feature
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: >
      Please ensure that there is not an issue open for this feature request (this helps me get to
      issues and features faster!)
      options:
        - label: I have searched for this feature in the existing issues
          required: true
  # Feature description
  - type: textarea
    attributes:
      label: Feature Description
      description: What is the feature you are requesting? Give a clear description of the feature
    validations:
      required: true
  # Other solutions
  - type: textarea
    attributes:
      label: Other Solutions
      description: Describe any other solutions to this issue you have considered
    validations:
      required: false
  # Anything else
  - type: textarea
    attributes:
      label: Anything Else?
      description: Is there anything else you would like to add?
      placeholder: |
        Add any extra information you have here.

        Pro-tip: You can drag files into this area! You can upload information like log files to this box!
    validations:
      required: false